<?php

namespace App\Entity\Radius;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByGroup($group = null)
    {
        @ini_set("memory_limit",-1);

        $this->getAllAccountingSums();

        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('u', 'rc', 'ug'/*, 'ra'*/)
            ->from(User::class, 'u')
            ->leftJoin('u.radiusCheck', 'rc')
            ->leftJoin('u.userGroups', 'ug')
            ->leftJoin('ug.group', 'groups');
            //->leftJoin('u.radiusAccounting', 'ra');

        if ($group) {
            $query->where('groups.name = :groupname')
                ->setParameter('groupname', $group);
        }
        return $query->getQuery()->getResult();
    }

    public function findByUsername($username)
    {

        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('u', 'rc', 'ug', 'ra')
            ->from(User::class, 'u')
            ->leftJoin('u.radiusCheck', 'rc')
            ->leftJoin('u.userGroups', 'ug')
            ->leftJoin('ug.group', 'groups')
            ->leftJoin('u.radiusAccounting', 'ra');

        $query->where('u.username = :username')
            ->setParameter('username', $username);

        return $query->getQuery()->getResult();
    }

    private function getAllAccountingSums() {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('u.username',  'SUM(ra.acctinputoctets) + SUM(ra.acctoutputoctets) AS AcctTotalOctets')
            ->from(User::class, 'u')
            ->join('u.radiusAccounting', 'ra')
            ->indexBy('u', 'u.username')
            ->groupBy('u.username');
        dump($query->getQuery()->getArrayResult());
    }
}
