grase_radmin_homepage:
    #path:     /hello/{name}
    path:     /
    defaults: { _controller: App\Controller\DefaultController::indexAction }


grase_users:
    path: /users/{group}
    defaults:
        _controller: App\Controller\UserController::displayUsersAction
        group: null

grase_user_edit:
    path: /user/{id}/edit
    defaults:
        _controller: App\Controller\UserController::editUserAction

grase_user_new:
    path: /user/new
    defaults:
        _controller: App\Controller\UserController::createUserAction

grase_groups:
    path: /groups/
    defaults:
        _controller: App\Controller\GroupController::displayGroupsAction

grase_group_edit:
    path: /group/{id}/edit
    defaults:
        _controller: App\Controller\GroupController::editGroupAction

grase_advanced_settings:
    path: /settings/advanced
    defaults:
        _controller: App\Controller\DefaultController::advancedSettingsAction

grase_dhcp_leases:
    path: /leases
    defaults:
        _controller: App\Controller\DefaultController::dhcpLeasesAction

grase_auditlog:
    path: /audit
    defaults:
        _controller: App\Controller\DefaultController::auditLogDisplayAction

#grase_security:
#    resource: "@App/Controller/SecurityController.php"
#    type:     annotation
