
jessie-all:
  stage: build
  image: grase/build-images:jessie
  variables:
    DISTRO: "jessie"
  script:
    - ./build.sh
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

trusty-all:
  stage: build
  image: grase/build-images:trusty
  variables:
    DISTRO: "trusty"
  script:
    - ./build.sh
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

xenial-all:
  stage: build
  image: grase/build-images:xenial
  variables:
    DISTRO: "xenial"
  script:
    - ./build.sh
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
