
jessie-all:
  stage: build
  image: grase/build-images:jessie
  script:
    - ./build.sh
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
    - mv -v ../grase-www-portal-ext-libs_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

trusty-all:
  stage: build
  image: grase/build-images:trusty
  script:
    - ./build.sh
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

xenial-all:
  stage: build
  image: grase/build-images:xenial
  script:
    - ./build.sh
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
