
jessie-all:
  image: grase/build-images:jessie
  script:
    - ./build.sh  
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

trusty-all:
  image: grase/build-images:trusty
  script:
    - ./build.sh  
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week



