
jessie-amd64:
  image: grase/build-images:jessie
  script:
    - ./build.sh  
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

trusty-amd64:
  image: grase/build-images:trusty
  script:
    - ./build.sh  
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week


jessie-i386:
  image: grase/build-images:jessie
  script:
    - ./build.sh   -ai386 -d
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

jessie-armhf:
  image: grase/build-images:jessie
  script:
    - ./build.sh   -aarmhf -d
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

jessie-armel:
  image: grase/build-images:jessie
  script:
    - ./build.sh   -aarmel -d
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
