stages:
  - dependencies
  - test
  - build

composer:
  image: grase/build-images:bionic
  stage: dependencies
  script:
    - cd files/usr/share/grase/symfony4/
    - composer install
  artifacts:
    paths:
      - files/usr/share/grase/symfony4/vendor/
    expire_in: 1 day

phpcs:
  image: grase/build-images:bionic
  stage: test
  dependencies:
    - composer
  script:
    - cd files/usr/share/grase/symfony4/
    - ./vendor/bin/phpcs -s

php-cs-fixer:
  image: grase/build-images:bionic
  stage: test
  dependencies:
    - composer
  script:
    - cd files/usr/share/grase/symfony4/
    #- vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --diff --using-cache=no
    - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no

.build_template: &build_definition
  stage: build
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-www-portal_* artifacts/
    - mv -v ../grase-www-portal-ext-libs_* artifacts/
  dependencies:
    - composer
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

bionic-all:
  <<: *build_definition
  image: grase/build-images:bionic
