api_platform:
    mapping:
        paths:
          - '%kernel.project_dir%/src/Entity'
          - '%kernel.project_dir%/config/api_platform/resources.yaml'
    collection:
        pagination:
            items_per_page: 15
            enabled: true
            page_parameter_name: _page
            enabled_parameter_name: pagination
