api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            items_per_page: 15
            enabled: true
            page_parameter_name: _page