#!/usr/bin/perl
use POSIX;

# Log in the mtotacct table aggregated accounting information for
# each user spaning in one month period.
# It will always log for last month, doing a complete month
# Works only with mysql and postgresql
#

$conf=shift||'/etc/radmin.conf';


open CONF, "<$conf"
	or die "Could not open configuration file\n";
while(<CONF>){
	chomp;
	($key,$val)=(split /:\s*/,$_);
	$sql_type = $val if ($key eq 'sql_type');
	$sql_server = $val if ($key eq 'sql_server');
	$sql_username = $val if ($key eq 'sql_username');
	$sql_password = $val if ($key eq 'sql_password');
	$sql_database = $val if ($key eq 'sql_database');
	$sqlcmd = $val if ($key eq 'sql_command');
}
close CONF;

die "sql_command directive is not set in radmin.conf\n" if ($sqlcmd eq '');
die "Could not find sql binary. Please make sure that the \$sqlcmd variable points to the right location\n" if (! -x $sqlcmd);

$sql_password = ($sql_password eq '') ? '' : "-p$sql_password";

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime;
#if ($mday == 1){
$mon--;
#}
$date_start = POSIX::strftime("%Y-%m-%d",0,0,0,1,$mon,$year,$wday,$yday,$isdst);
$date_end = POSIX::strftime("%Y-%m-%d",0,0,0,1,$mon+1,$year,$wday,$yday,$isdst);

$query1 = "INSERT INTO mtotaccttmp (UserName,AcctDate,ConnNum,ConnTotDuration,ConnMaxDuration,ConnMinDuration,InputOctets,OutputOctets,NASIPAddress) SELECT UserName,'$date_start',COUNT(*),SUM(AcctSessionTime),MAX(AcctSessionTime),MIN(AcctSessionTime),SUM(AcctInputOctets), SUM(AcctOutputOctets),NASIPAddress FROM radacct WHERE AcctStopTime >= '$date_start' AND AcctStopTime < '$date_end' GROUP BY UserName,NASIPAddress;";
$query2 = "DELETE FROM radacct WHERE AcctStopTime >= '$date_start' AND AcctStopTime < '$date_end';";

$query3 = "UPDATE radcheck,mtotaccttmp SET radcheck.value=radcheck.value - (mtotaccttmp.InputOctets + mtotaccttmp.OutputOctets) WHERE radcheck.Attribute='Max-Octets' AND radcheck.UserName=mtotaccttmp.UserName AND mtotaccttmp.AcctDate='$date_start';";

$query4 = "UPDATE radcheck,mtotaccttmp SET radcheck.value=radcheck.value - mtotaccttmp.ConnTotDuration WHERE radcheck.Attribute='Max-All-Session' AND radcheck.UserName=mtotaccttmp.UserName AND mtotaccttmp.AcctDate='$date_start';";

$query5 ="INSERT INTO mtotacct (UserName,AcctDate,ConnNum,ConnTotDuration,ConnMaxDuration,ConnMinDuration,InputOctets,OutputOctets,NASIPAddress) SELECT UserName,AcctDate,ConnNum,ConnTotDuration,ConnMaxDuration,ConnMinDuration,InputOctets,OutputOctets,NASIPAddress FROM mtotaccttmp;";

$query6 = "TRUNCATE mtotaccttmp;";

$query7 = "UPDATE radcheck SET radcheck.value=0 WHERE radcheck.Attribute='Max-Octets' AND radcheck.value < 0;";

$query8 = "DELETE FROM radacct WHERE AcctStopTime < '$date_end';";

#print "$query1\n";
#print "$query2\n";
#print "$query3\n";
#print "$query4\n";
#print "$query5\n";
#print "$query6\n";
open TMP, ">/tmp/tot_stats.query"
	or die "Could not open tmp file\n";
print TMP $query1;
print TMP $query2;
print TMP $query3;
print TMP $query4;
print TMP $query5;
print TMP $query6;
print TMP $query7;
print TMP $query8;
close TMP;
$command = "$sqlcmd -v -v -h $sql_server -u $sql_username $sql_password $sql_database </tmp/tot_stats.query" if ($sql_type eq 'mysql');
$command = "$sqlcmd  -U $sql_username -f /tmp/tot_stats.query $sql_database" if ($sql_type eq 'pg');
print `$command`;
