#!/usr/bin/perl
use POSIX;

# Remove stale sessions from accounting database
#

$conf=shift||'/etc/radmin.conf';


open CONF, "<$conf"
	or die "Could not open configuration file\n";
while(<CONF>){
	chomp;
	($key,$val)=(split /:\s*/,$_);
	$sql_type = $val if ($key eq 'sql_type');
	$sql_server = $val if ($key eq 'sql_server');
	$sql_username = $val if ($key eq 'sql_username');
	$sql_password = $val if ($key eq 'sql_password');
	$sql_database = $val if ($key eq 'sql_database');
	$sqlcmd = $val if ($key eq 'sql_command');
}
close CONF;

die "sql_command directive is not set in radmin.conf\n" if ($sqlcmd eq '');
die "Could not find sql binary. Please make sure that the \$sqlcmd variable points to the right location\n" if (! -x $sqlcmd);

$sql_password = ($sql_password eq '') ? '' : "-p$sql_password";

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime;
$mon--;
$date_start = POSIX::strftime("%Y-%m-%d",0,0,0,1,$mon,$year,$wday,$yday,$isdst);
$date_end = POSIX::strftime("%Y-%m-%d",0,0,0,1,$mon+1,$year,$wday,$yday,$isdst);

$query1 = "UPDATE radacct SET AcctTerminateCause='Admin-Reset', AcctStopTime = FROM_UNIXTIME(UNIX_TIMESTAMP(AcctStartTime) + AcctSessionTime) WHERE AcctStopTime = 0 AND TIME_TO_SEC(TIMEDIFF(NOW(), ADDTIME(AcctStartTime,SEC_TO_TIME(AcctSessionTime)))) > 300 AND TIME_TO_SEC(TIMEDIFF(NOW(),AcctStartTime)) > 43200;";

#print "$query1\n";
open TMP, ">/tmp/stale_sessions.query"
	or die "Could not open tmp file\n";
print TMP $query1;
close TMP;
$command = "$sqlcmd -v -v -h $sql_server -u $sql_username $sql_password $sql_database </tmp/stale_sessions.query" if ($sql_type eq 'mysql');
$command = "$sqlcmd  -U $sql_username -f /tmp/stale_sessions.query $sql_database" if ($sql_type eq 'pg');
print `$command`;
