#!/usr/bin/perl
use POSIX;

# Delete expired users older than 3 months
# Works only with mysql and postgresql
#

$conf=shift||'/etc/radmin.conf';


open CONF, "<$conf"
	or die "Could not open configuration file\n";
while(<CONF>){
	chomp;
	($key,$val)=(split /:\s*/,$_);
	$sql_type = $val if ($key eq 'sql_type');
	$sql_server = $val if ($key eq 'sql_server');
	$sql_username = $val if ($key eq 'sql_username');
	$sql_password = $val if ($key eq 'sql_password');
	$sql_database = $val if ($key eq 'sql_database');
	$sqlcmd = $val if ($key eq 'sql_command');
}
close CONF;

die "sql_command directive is not set in radmin.conf\n" if ($sqlcmd eq '');
die "Could not find sql binary. Please make sure that the \$sqlcmd variable points to the right location\n" if (! -x $sqlcmd);

$sql_password = ($sql_password eq '') ? '' : "-p$sql_password";

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime;
#if ($mday == 1){
#}
$date_old = POSIX::strftime("%B%%%Y 00:00:00",0,0,0,1,$mon-3,$year,$wday,$yday,$isdst);
$date_start = POSIX::strftime("%Y-%m-%d",0,0,0,1,$mon-1,$year,$wday,$yday,$isdst);
$date_end = POSIX::strftime("%Y-%m-%d",0,0,0,1,$mon,$year,$wday,$yday,$isdst);
$query1 = "DELETE FROM radcheck WHERE username IN (SELECT UserName FROM (SELECT UserName FROM radcheck WHERE Attribute = 'Expiration' AND Value LIKE '$date_old') AS temptable);";
#die "$query1";
#print "$query1\n";
#print "$query2\n";
#print "$query3\n";
#print "$query4\n";
#print "$query5\n";
#print "$query6\n";
open TMP, ">/tmp/tot_stats.query"
	or die "Could not open tmp file\n";
print TMP $query1;
close TMP;
$command = "$sqlcmd -v -v -h $sql_server -u $sql_username $sql_password $sql_database </tmp/tot_stats.query" if ($sql_type eq 'mysql');
$command = "$sqlcmd  -U $sql_username -f /tmp/tot_stats.query $sql_database" if ($sql_type eq 'pg');
print `$command`;
