#!/bin/sh
# postrm script for grase-www-portal

set -e
#set -u # Interfers with debconf


if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go grase-db $@
fi


if [ "$1" = "purge" ]; then

	# Remove symfony var folder
	rm -rf /usr/share/grase/symfony4/var

  # Remove our config files
  rm -f /usr/share/grase/symfony4/.env.local
  if which ucf >/dev/null 2>&1; then
          ucf --purge /usr/share/grase/symfony4/.env.local
          ucfr --purge grase-www-portal /usr/share/grase/symfony4/.env.local
  fi
fi

#DEBHELPER#

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /etc/apache2/conf.d/grase.conf -- "$@"
fi
