#!/bin/sh -e

action="$1"
oldversion="$2"

umask 022

# source debconf stuff
. /usr/share/debconf/confmodule
# source dbconfig-common stuff
. /usr/share/dbconfig-common/dpkg/postinst.mysql

mkdir -p /etc/grase/

dbc_first_version=3.0
dbc_generate_include="template:/usr/share/grase/symfony4/.env.local"
dbc_generate_include_perms="660"
dbc_generate_include_owner="root:www-data"
dbc_generate_include_args="-o template_infile=/usr/share/grase/templates/env.local -U"

dbc_go grase-db $@

if [ "$action" != configure ]
  then
  exit 0
fi


call_cron(){ # Call cron so certain upgrades can occur
    runuser -u www-data -- /usr/share/grase/symfony4/bin/console grase:cron:runner
}

fix_dir_perms(){
    chgrp www-data -R /usr/share/grase/symfony4/var/ || true
    chmod ag+rw -R /usr/share/grase/symfony4/var/ >/dev/null 2>&1 || true
    chmod ag+rw /usr/share/grase/www/images || true

}

copy_favicon(){
    cp -n /usr/share/grase/www/favicon.ico /var/www/favicon.ico || true
}

run_migrations(){
    runuser -u www-data -- /usr/share/grase/symfony4/bin/console doctrine:migrations:migrate --no-interaction || true
}

prod_cache(){
    runuser -u www-data -- /usr/share/grase/symfony4/bin/console cache:clear || true
    runuser -u www-data -- /usr/share/grase/symfony4/bin/console cache:warmup || true
}

fix_settings(){
    /usr/share/grase/symfony4/bin/console grase:settings-validate || true
}

#DEBHELPER#

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /etc/apache2/conf.d/grase.conf -- "$@"
fi


fix_dir_perms

copy_favicon

run_migrations

prod_cache

fix_settings

#a2enmod rewrite || true
#a2enmod headers || true

#if which invoke-rc.d >/dev/null 2>&1; then
#       invoke-rc.d apache2 restart 3>&- || true
#else
#       /etc/init.d/apache2 restart 3>&- || true
#fi

# Display message about first-run wizard
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' '='
cat <<"EOF"
If this is the first time running the Grase Hotspot Install
please run the first-run wizard to get started:
  sudo -u www-data /usr/share/grase/symfony4/bin/console grase:first-run
EOF
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' '='

exit 0
