#!/bin/sh -e

action="$1"
oldversion="$2"

umask 022

# source debconf stuff
. /usr/share/debconf/confmodule
# source dbconfig-common stuff
. /usr/share/dbconfig-common/dpkg/postinst.mysql

mkdir -p /etc/grase/

dbc_first_version=3.0
dbc_generate_include="template:/etc/grase/radmin.conf"
dbc_generate_include_perms="660"
dbc_generate_include_owner="root:www-data"
dbc_generate_include_args="-o template_infile=/usr/share/grase/templates/radmin.conf -U"

dbc_go grase-www-portal $@



if [ "$action" != configure ]
  then
  exit 0
fi

install_composer_deps(){ # Install composer and install/upgrade dependencies
    cd /usr/share/grase/
    if [ ! -e 'composer.phar' ]; then
        curl -sS https://getcomposer.org/installer | php
    fi
    php composer.phar self-update
    php composer.phar install
}

install_bower_deps(){ # Install Bower and install/upgrade depenencies
    cd /usr/share/grase/
    npm install -g bower
    bower update
}

call_cron(){ # Call cron so certain upgrades can occur
    wget -q http://127.0.0.1/grase/radmin/cron.php -O - || true
}

fix_dir_perms(){
	chgrp www-data -R /usr/share/grase/www/ || true
	chmod ag+rw -R /usr/share/grase/www/images/logo.png /usr/share/grase/www/radmin/templates_c /usr/share/grase/www/uam/templates_c || true
	chmod a+rw -R /usr/share/grase/www/public/* || true

}

clear_template_cache(){
    rm -f /usr/share/grase/www/radmin/templates_c/* /usr/share/grase/www/uam/templates_c/*
}

copy_favicon(){
    cp -n /usr/share/grase/www/favicon.ico /var/www/favicon.ico || true
}

link_logo(){
    #if [[ ! -a /usr/share/grase/www/images/logo.png ]]
    #then
    
    # Don't worry about tests, will fail silently
    ln -s graselogo.png /usr/share/grase/www/images/logo.png > /dev/null || true
    #fi

}

www_proxy_group(){
    # www-data needs to be in proxy for log processing
    adduser www-data proxy > /dev/null || true
}
#DEBHELPER#

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /etc/apache2/conf.d/grase.conf -- "$@"
fi

link_logo

clear_template_cache

install_composer_deps

install_bower_deps

fix_dir_perms

copy_favicon

call_cron

www_proxy_group

#a2enmod rewrite || true
#a2enmod headers || true

#if which invoke-rc.d >/dev/null 2>&1; then
#       invoke-rc.d apache2 restart 3>&- || true
#else
#       /etc/init.d/apache2 restart 3>&- || true
#fi


exit 0


