#!/bin/sh -e

action="$1"
oldversion="$2"

umask 022

# source debconf stuff
. /usr/share/debconf/confmodule
# source dbconfig-common stuff
. /usr/share/dbconfig-common/dpkg/postinst.mysql

mkdir -p /etc/grase/

dbc_first_version=3.0
dbc_generate_include="template:/etc/grase/radmin.conf"
dbc_generate_include_perms="660"
dbc_generate_include_owner="root:www-data"
dbc_generate_include_args="-o template_infile=/usr/share/grase/templates/radmin.conf -U"

dbc_go grase-www-portal $@



if [ "$action" != configure ]
  then
  exit 0
fi


call_cron(){ # Call cron so certain upgrades can occur
    REMOTE_ADDR='' php /usr/share/grase/www/radmin/cron.php || true
}

fix_dir_perms(){
    chgrp www-data -R /usr/share/grase/symfony4/var/ || true
    chmod ag+rw -R /usr/share/grase/symfony4/var/ >/dev/null 2>&1 || true
    chmod ag+rw /usr/share/grase/www/images || true

}

copy_favicon(){
    cp -n /usr/share/grase/www/favicon.ico /var/www/favicon.ico || true
}

www_proxy_group(){
    # www-data needs to be in proxy for log processing
    adduser www-data proxy > /dev/null || true
}

run_migrations(){
    runuser -u www-data /usr/share/grase/symfony4/bin/console doctrine:migrations:migrate --no-interaction || true
}

fix_settings(){
    # TODO This is going to end up as part of the migrations, so probably not needed here
    /usr/share/grase/symfony4/bin/console grase:settings-validate || true
}

#DEBHELPER#

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /etc/apache2/conf.d/grase.conf -- "$@"
fi


fix_dir_perms

copy_favicon

run_migrations

fix_settings

# call_cron

www_proxy_group

#a2enmod rewrite || true
#a2enmod headers || true

#if which invoke-rc.d >/dev/null 2>&1; then
#       invoke-rc.d apache2 restart 3>&- || true
#else
#       /etc/init.d/apache2 restart 3>&- || true
#fi


exit 0


