gettext("Username");
gettext("Choose a username");
gettext("Password");
gettext("Choose a secure password for the user");
gettext("Group");
gettext("Choose the users group (Expiry is based on the user group)");
gettext("Comment");
gettext("A comment about the user");
gettext("When ether limit is reached, the user will be cut off. (i.e. after 1hour even if they still have data left)");
gettext("A limit of 0 does not mean unlimited, it will immediately lock the user out. To have an unlimited user, the user must be created without any limits.");
gettext("Data Limit (MiB)");
gettext("OR");
gettext("Type your own Mb Limit");
gettext("Choose a Data Limit OR Type your own value");
gettext("Time Limit (Minutes)");
gettext("OR");
gettext("Type your own Time Limit");
gettext("Choose a Time Limit OR Type your own value");
gettext("User Management Interface");
gettext("Device Information");
gettext("Model Name");
gettext("Host Name");
gettext("System Up-Time");
gettext("Current Server Time");
gettext("Hardware Version");
gettext("Software Version");
gettext("Home URL");
gettext("LAN");
gettext("IP Address");
gettext("Subnet Mask");
gettext("MAC Address");
gettext("Network Interface");
gettext("WAN");
gettext("IP Address");
gettext("Subnet Mask");
gettext("Gateway");
gettext("DNS 1");
gettext("DNS 2");
gettext("MAC Address");
gettext("Network Interface");
gettext("Login");
gettext("Login is required to access the Administration section of this website.");
gettext("Username");
gettext("Username for Admin interface (Different to internet access username)");
gettext("Password");
gettext("Login");
gettext("Site Settings");
gettext("Location Name");
gettext("Enter a name that identifies this Hotspot Location");
gettext("Support Contact Name");
gettext("Enter the name of the Support Contact");
gettext("Support Link");
gettext("This is the link for the support contact. http:// or mailto: are allowed. If using http:// ensure this is accessabile for users who aren't logged into the hotspot");
gettext("Locale");
gettext("Select the appropriate Locale for your location");
gettext("A locale has 2 parts, the language and location.<br/><strong>en_AU</strong> for example has the Language set to English, and the location to Australia.<br/><strong>en_ZA</strong> has the language set to English, and the location to South Africa, while <strong>af_ZA</strong> has the language set to Afrikaans and the location to South Africa.");
gettext("The locale defines the number formats, currency and language. If the language selected is not available, it will fallback to English.");
gettext("Current locale is <strong>%1</strong>, which sets the language to <strong>%2</strong>, and location to <strong>%3</strong>.");
gettext("Currency symbol is <strong>%1</strong>");
gettext("Currency");
gettext("Select the appropriate symbol for your local currency");
gettext("How much to charge per Mb");
gettext("Cost per Minute");
gettext("How much to charge per Minute");
gettext("Website Name");
gettext("Label for Website Footer link");
gettext("Website Link");
gettext("Link for Website Footer Link");
gettext("Sellable Graph Max");
gettext("Select what is 100% on the Sellable Data Graph");
gettext("Useable Graph Max");
gettext("Select what is 100% on the Useable Data Graph");
gettext("Save Settings");
gettext("Group Config");
gettext("Group expiry needs to be in a format understood by the <a target=\"_blank\" href=\"http://www.php.net/manual/en/function.strtotime.php\">strtotime</a> PHP function.");
gettext("For example, \"+1 month\" will set an expiry for 1 month from when the account is created. \"+2 weeks\", \"+3 days\" etc.");
gettext("Deleting a group won't delete it's users. Next time the user is edited it's group will become the default group unless a new group is selected.");
gettext("Group Name and Expiry");
gettext("Save Settings");
gettext("Edit User");
gettext("Computer Account Locked (Only comments can be changed)");
gettext("Username");
gettext("Comment");
gettext("Group");
gettext("Data Limit (MiB)");
gettext("Expiry");
gettext("Comment");
gettext("Change Comment");
gettext("Change Comment");
gettext("If you really want to delete this machine account, please type exactly \"Yes, I want to delete this user\" in the below box then click \"Delete User\"");
gettext("Delete User");
gettext("Delete User");
gettext("Username");
gettext("Password");
gettext("Choose a secure password for the user. Leave blank to not change");
gettext("Choose the users group (Expiry is based on the user group)");
gettext("Comment");
gettext("A comment about the user");
gettext("When ether limit is reached, the user will be cut off. (i.e. after 1hour even if they still have data left)");
gettext("A limit of 0 does not mean unlimited, it will immediately lock the user out. To have an unlimited user, the user must be created without any limits.");
gettext("Data Limit (MiB)");
gettext("Type your own Mb Limit");
gettext("Change the Data Limit");
gettext("Add Data to Limit (MiB)");
gettext("Add to the Data Limit (Will ignore changes made above)");
gettext("Time Limit (Minutes)");
gettext("Type your own Time Limit");
gettext("Change the Time Limit");
gettext("Add Time to Limit (Minutes)");
gettext("Add to the Time Limit (Will ignore changes made above)");
gettext("Update User Details");
gettext("Update User Details");
gettext("If you really want to delete a user, please type exactly \"Yes, I want to delete this user\" in the below box then click \"Delete User\"");
gettext("Delete the User");
gettext("Delete User");
gettext("Delete User");
gettext("Portal Settings");
gettext("These settings are used by Coova Chilli. Coova Chilli only reloads it's config roughly once an hour, or when it's restarted.");
gettext("If you change the MAC Auth Password, no computer accounts will be able to login until Coova Chilli reloads it's config, or is manually restarted.");
gettext("Chilli Config last updated %1");
gettext("Portal Config last updated %1");
gettext("For each of the following items, if you need multiple values you can submit the form and it will append a blank input below the last valid value");
gettext("Save Settings");
gettext("Sessions for %1");
gettext("Start Time");
gettext("Stop Time");
gettext("Time");
gettext("IP Address");
gettext("Username");
gettext("Download");
gettext("Uploaded");
gettext("Data Usage");
gettext("Reason: ");
gettext("Computers hardware (MAC) address is %1");
gettext("Captive Portal Config Login");
gettext("Upload Logo");
gettext("Logo Image");
gettext("Select new logo file.");
gettext("Logo file needs to be in png format, and relatively small (remember, every page has the logo). 10 Kilobytes maximum. It's physical size shouldn't be bigger than about 220px in both directions.");
gettext("Upload Logo");
gettext("Admin Users");
gettext("Change Password");
gettext("Username");
gettext("Old Password");
gettext("New Password");
gettext("Confirm New Password");
gettext("Change Password");
gettext("Change Password");
gettext("Create new Admin User");
gettext("Username");
gettext("Password");
gettext("Create new Admin User");
gettext("Delete Admin User");
gettext("Deleting or modifying the support user will prevent remote assistance.");
gettext("Are you sure you want to delete %1?");
gettext("Delete %1");
gettext("Cannot delete current user");
gettext("Logged in as <b>%1</b>");
gettext("Session logs for %1 on %2");
gettext("Computers hardware (MAC) address is");
gettext("Between %1 and %2");
gettext("Total HTTP (WWW) Traffic Size:");
gettext("Domain");
gettext("Count");
gettext("Size");
gettext("Timestamp");
gettext("Address");
gettext("Host");
gettext("Cached");
gettext("Request Type");
gettext("Size");
gettext("Help Page");
gettext("My Account");
gettext("Admin");
gettext("Username");
gettext("Group");
gettext("Data Limit");
gettext("Total Data usage for the current month");
gettext("Data Usage (M)");
gettext("Total Data usage, from previous months, excluding current month");
gettext("Data Usage (T)");
gettext("Time Limit");
gettext("Time Usage (Month)");
gettext("Account Expiry");
gettext("Last Logoff timestamp from current month only");
gettext("Last Logoff");
gettext("Comment");
gettext("Password Hidden");
gettext("Admin Log");
gettext("Timestamp");
gettext("Username");
gettext("IP");
gettext("Action");
gettext("Error");
gettext("An Error has occured. Please report the error to the administrator");
gettext("There may be more information available to the administrator in the logs");
gettext("Create Computer Account");
gettext("MAC Address");
gettext("The MAC address is the network hardware address of the computer. It needs to be of the format XX-XX-XX-XX-XX-XX where XX is a hex number, typed in all capitals");
gettext("Comment");
gettext("Identify the computer. i.e. \"Bob's computer\"");
gettext("When ether limit is reached, the user will be cut off. (i.e. after 1hour even if they still have data left)");
gettext("Computer accounts are intended to be used for computers that need internet access at all times. For example, an office computer. Computer accounts login automatically as soon as they access the network, this will normally occur at startup. If a limit is set, when the limit is reached the computer will revert to the normal login screen for internet access. Computer accounts can not be edited to add more data or time, only deleted.");
gettext("It is not recommended setting a time or data limit for computer accounts.");
gettext("Data Limit (MiB)");
gettext("OR");
gettext("Type your own Mb Limit");
gettext("Time Limit (Minutes)");
gettext("OR");
gettext("Type your own Time Limit");
gettext("Choose a Time Limit OR Type your own value");
gettext("Create New Computer Account");
gettext("Create New Computer Account");
gettext("Sold");
gettext("%1 of %2");
gettext("This Month Used");
gettext("%1 of %2");
gettext("Last Month Used");
gettext("%1 of %2");
