version: "3.6"
services:

    webserver:
      build: .
      volumes:
        - ../:/usr/share/grase


    mysql:
      image: mariadb:10.1
      volumes:
        - ./db_initial:/docker-entrypoint-initdb.d/
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=radius
        - MYSQL_USER=grase
        - MYSQL_PASSWORD=grase

    adminer:
      image: adminer
      environment:
        - ADMINER_DESIGN=nette
        - ADMINER_DEFAULT_SERVER=mysql

    node:
      image: node:8
      volumes:
        - ../:/usr/share/grase
      working_dir: /usr/share/grase/symfony4
