<?php

namespace Grase\RadminBundle\Entity\Radius;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByGroup($group = null)
    {

        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('u', 'rc', 'ug')
            ->from('GraseRadminBundle:Radius\User', 'u')
            ->leftJoin('u.radiuscheck', 'rc')
            ->leftJoin('u.usergroups', 'ug');
        /* TODO add group filtering
        if ($group)
        {
            $query->where('1=1')
            ->setParameter('group',$groupid)
            ->setParameter('string', '%'.$string.'%')
        }*/
        return $query->getQuery()->getResult();


    }

}
