gettext("You are logged in as:");
gettext("User");
gettext("Usage this session");
gettext("Remaining Quota");
gettext("Unlimited");
gettext("Quota allocation");
gettext("Unlimited");
gettext("Max Session Time");
gettext("Max Idle Time");
gettext("Start Time");
gettext("Session Time");
gettext("Remaining Time");
gettext("Unlimited");
gettext("Time Limit");
gettext("Unlimited");
gettext("Idle Time");
gettext("Downloaded");
gettext("Uploaded");
gettext("Help");
gettext("Support");
gettext("Successful Login");
gettext("Continue to your site");
gettext("Free Downloads");
gettext("Welcome to the %1 Hotspot. Please read the following before logging in.");
gettext("Information and Help");
gettext("For a quick logout, bookmark <a href=\"%1\">LOGOUT</a>");
gettext("If you are already logged in, continue to your site");
gettext("You are using the less secure login method.");
gettext("If you have javascript disabled, please try enabling it for the secure login method.");
gettext("Use this less secure login form if the javascript version is giving you trouble");
gettext("You have disabled the secure javascript login method.");
gettext("Click here to re-enable it");
gettext("Username");
gettext("Password");
gettext("Trouble logging in?");
gettext("Click here to disable the javascript login forms.");
gettext("This will use a less secure login method");
gettext("Error");
gettext("An Error has occured. Please report the error to the administrator");
