gettext("Login");
gettext("Help");
gettext("Please enable Javascript to use this hotspot, or use a device that supports javascript");
gettext("Successful Login");
gettext("Continue to your site");
gettext("My Account");
gettext("Support");
gettext("Admin");
gettext("By continuing, you agree to the below terms and conditions.");
gettext("Show Terms and Conditions");
gettext("If you are already logged in, continue to your site");
gettext("Voucher Login");
gettext("Username");
gettext("Password");
gettext("Attempting Login...");
gettext("Logged in as");
gettext("Remaining Session Time");
gettext("Remaining Session Data");
gettext("Logout");
gettext("Open Status Window");
gettext("Trouble logging in?");
gettext("Click here to try a less secure login.");
gettext("You have disabled the secure javascript login method.");
gettext("Click here to re-enable it");
gettext("Help");
gettext("You are logged in as:");
gettext("Access My Account");
gettext("User");
gettext("Usage this session");
gettext("Remaining Quota");
gettext("Unlimited");
gettext("Quota allocation");
gettext("Unlimited");
gettext("Max Session Time");
gettext("Not available");
gettext("Max Idle Time");
gettext("Not available");
gettext("Start Time");
gettext("Session Time");
gettext("Remaining Time");
gettext("Unlimited");
gettext("Time Limit");
gettext("Unlimited");
gettext("Idle Time");
gettext("Not available");
gettext("Downloaded");
gettext("Uploaded");
gettext("Error");
gettext("An Error has occured. Please report the error to the administrator");
